version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_COLLECTION=${DB_COLLECTION}
      # - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_HOST}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
